# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  compile_latex_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v2
      - run: chmod +x public/files
      - run: git rm public/files/round1.pdf
      - run: git rm public/files/round2.pdf
      - name: Compile Round 1 LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: round1.tex  # gets appended to pandoc command
          working_directory: public/files/
          args: -f -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - run: git add public/files/round1.pdf -f
      - name: Compile Round 2 LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: round2.tex  # gets appended to pandoc command
          working_directory: public/files/
          args: -f -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - run: git add public/files/round2.pdf -f 
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: westmuse
          author_email: 64872597+westmuse@users.noreply.github.com
          message: "Convert latex files to pdf"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
